"""relation

Revision ID: 0e709da0dc76
Revises: 71148e8772fa
Create Date: 2024-11-11 21:23:03.428079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e709da0dc76'
down_revision = '71148e8772fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_created', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_created'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_created')

    # ### end Alembic commands ###
