"""relation

Revision ID: a92771dc0a20
Revises: 0e709da0dc76
Create Date: 2024-11-11 21:35:45.561199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92771dc0a20'
down_revision = '0e709da0dc76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('user_created',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('user_created',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
